const translateConfig = {
    "TH":{
        "ข้อความแนะนำ":"ระบบโปรโมชั่นการสะสมคะแนนในการแลก เพื่อเพิ่มความคุ้มค่าและความประทับใจ ในการซื้อซ้ำ",
        "เพลิดเพิลนไปกับการซื้อซ้ำ":"เพื่อความคุ้มค่าและความประทับใจใน การกลับมาซื้อในครั้งต่อๆไป",
        "อธิบายลูกค้า":"ใช้บริการกับร้านค้าที่ร่วมรายการภายในแอพของเรา",
        "อธิบายแอดมิน":"ดูแลการใช้งานการบริการโปรโมชั่นต่างๆ ภายในร้านค้า",
        "อธิบายสะสมคะแนน":"ระบบสะสมคะแนนที่เกิดขึ้นหลังจากลูกค้าที่ใช้บริการภายในแอพ",
        "อธิบายโปรโมชั่น":"มองหาโปรโมชั่นที่น่าสนใจจากหลากหลายร้านค้าที่ให้บริการ",
        "อธิบายร้านค้า":"สำรวจแผนผังลายระเอียการซื้อขายของกลุ่มลูกค้า",
        "ยินดีให้บริการ":"ทางเรายินดีให้บริการ ทางด้านการเพิ่มโปรโมชั่นที่ช่วยสร้าง ความประทับใจ ความคุ้มค่าเมื่อลูกค้าได้กลับมา ซื้อซ้ำ.",
        "ที่อยู่ๆ":"บริษัท ไอเดียล แอพโพรช จำกัด เลขที่ 2 ซอยกรุงเทพกรีฑา 19 แขวงทับช้าง เขตสะพานสูง กรุงเทพฯ 10250"
      },
      "EN":{
        "ที่อยู่ๆ": " IDEAL APPROACH CO., LTD 2 Soi Krungthep Kritha 19, Thap Chang, Saphan Sung, Bangkok. 10250	",
        "เพื่อประสบการณ์การที่ดีสำหรับลูกค้า":"For the good experience for customers",
        "ที่อยู่":"address",
        "ช่องทางการติดต่อ":"contact way",
        "อื่นๆ":"Other",
        "ม็อคอัพ":"mock up",
        "หน้าแรก":"Home",
        "ฟีเจอร์":"Feature",
        "วิธีการใช้งาน":"Manual",
        "แพคเกจ":"Package",
        "ติดต่อเรา":"Contact US",
        "ข้อความแนะนำ":"Promotion systemCollect points for redemption To increase the value and impression of repeat purchases",
        "โปรดักเรามีการทำงานอย่างไร":"Process",
        "ลูกค้า":"Buyer",
        "อธิบายลูกค้า":"Use the service at participating stores within our app.",
        "แอดมิน":"Admin",
        "อธิบายแอดมิน":"Take care of the use of services, promotions, stores",
        "ร้านค้า":"Market",
        "อธิบายร้านค้า":"Explore how customers trade",
        "สิ่งที่ลูกค้าจะได้รับ":"Service",
        "สะสมคะแนน":"Point",
        "อธิบายสะสมคะแนน":"Points system for shopping through the app",
        "โปรโมชั่น":"Promotions",
        "อธิบายโปรโมชั่น":"promotions from a variety of shops that provide services.",
        "เพลิดเพลินไปกับการซื้อซ้ำ":"Good to Buying again.",
        "อธิบายเพลิดเพลินไปกับการซื้อซ้ำ":"Enjoy the pleasure of buying again.",
        "กลุ่มลูกค้าของเรา":"Our Partner",
        "ยินดีให้บริการ":"We are happy to serve. In the side of adding promotions that help create an impression of value When customers come back to buy again",
        "เปิดหน้าร้าน Line Official Account":"Line Official Account",
        "บริการที่ลูกค้าจะได้รับจากเรา":"Service",
        "ตัวอย่างบริการเปิดหน้าร้าน":"Example about market",
        "ระบบแผงควบคุม":"Dashboard System",
        "ระบบเพิ่มเพื่อน":"Friend Invite System",
        "ระบบสร้างแพคเกจ":"Package System",
        "ระบบสร้างโปรโมชั่น":"Promotion System",
        "ระบบสร้าง QR-code":"QR Code System",
        "ระบบรายงาน":"ReportSystem",
        "ระบบจัดการข้อมูลผู้ใช้งาน":"User Management System",
        "แพคเกจFunCrowds":"Package : Funcrowds",
        "แพคเกจWechat":"Package : Wechat",
        "แพคเกจLine":"Package : Line",
        "ติดต่อผ่านช่องทางหลัก":"Main contact way",
        "สมัครใช้บริการ":"Register"
      }
}

export default translateConfig;